ReadSpeaker.lib||(ReadSpeaker.lib={});
(function(C,K){function t(A,a,e,c){for(var d=0,da=a.length;d<da;d++)p(A,a[d],e,c)}function a(A,a,e){var c=a.dir,ca=W++;A||(A=function(A){return A===e});return a.first?function(a,b){for(;a=a[c];)if(1===a.nodeType)return A(a,b)&&a}:function(a,b){for(var e,f=ca+"."+g,h=f+"."+d;a=a[c];)if(1===a.nodeType){if((e=a[y])===h)return a.sizset;if("string"===typeof e&&0===e.indexOf(f)){if(a.sizset)return a}else{a[y]=h;if(A(a,b))return a.sizset=!0,a;a.sizset=!1}}}}function c(a,b){return a?function(e,c){var d=b(e,
c);return d&&a(!0===d?e:d,c)}:b}var d,g,f,h,s,r=C.document,k=r.documentElement,H=!1,X=!0,W=0,E=[].slice,I=[].push,y=("sizcache"+Math.random()).replace(".",""),B="\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[-\\w]|[^\\x00-\\xa0])+)[\\x20\\t\\r\\n\\f]*(?:([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:(['\"])((?:\\\\.|[^\\\\])*?)\\3|("+"(?:\\\\.|[-\\w]|[^\\x00-\\xa0])+".replace("w","w#")+")|)|)[\\x20\\t\\r\\n\\f]*\\]",z="(?=[^\\x20\\t\\r\\n\\f])(?:\\\\.|"+B+"|"+":((?:\\\\.|[-\\w]|[^\\x00-\\xa0])+)(?:\\((?:(['\"])((?:\\\\.|[^\\\\])*?)\\2|((?:[^,]|\\\\,|(?:,(?=[^\\[]*\\]))|(?:,(?=[^\\(]*\\))))*))\\)|)".replace(2,
7)+"|[^\\\\(),])+",M=RegExp("^[\\x20\\t\\r\\n\\f]+|((?:^|[^\\\\])(?:\\\\.)*)[\\x20\\t\\r\\n\\f]+$","g"),L=/^[\x20\t\r\n\f]*([\x20\t\r\n\f>+~])[\x20\t\r\n\f]*/,N=RegExp(z+"?(?=[\\x20\\t\\r\\n\\f]*,|$)","g"),Y=RegExp("^(?:(?!,)(?:(?:^|,)[\\x20\\t\\r\\n\\f]*"+z+")*?|[\\x20\\t\\r\\n\\f]*(.*?))(\\)|$)"),ea=RegExp(z.slice(19,-6)+"\\x20\\t\\r\\n\\f>+~])+|[\\x20\\t\\r\\n\\f]*([\\x20\\t\\r\\n\\f>+~])[\\x20\\t\\r\\n\\f]*","g"),fa=/^(?:#([\w\-]+)|(\w+)|\.([\w\-]+))$/,O=/[\x20\t\r\n\f]*[+~]/,ga=/:not\($/,ha=
/h\d/i,ia=/input|select|textarea|button/i,J=/\\(?!\\)/g,F={ID:/^#((?:\\.|[-\w]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[-\w]|[^\x00-\xa0])+)/,NAME:/^\[name=['"]?((?:\\.|[-\w]|[^\x00-\xa0])+)['"]?\]/,TAG:RegExp("^("+"(?:\\\\.|[-\\w]|[^\\x00-\\xa0])+".replace("[-","[-\\*")+")"),ATTR:RegExp("^"+B),PSEUDO:/^:((?:\\.|[-\w]|[^\x00-\xa0])+)(?:\((?:(['"])((?:\\.|[^\\])*?)\2|((?:[^,]|\\,|(?:,(?=[^\[]*\]))|(?:,(?=[^\(]*\))))*))\)|)/,CHILD:/^:(only|nth|last|first)-child(?:\([\x20\t\r\n\f]*(even|odd|(([+-]|)(\d*)n|)[\x20\t\r\n\f]*(?:([+-]|)[\x20\t\r\n\f]*(\d+)|))[\x20\t\r\n\f]*\)|)/i,
POS:RegExp(":(nth|eq|gt|lt|first|last|even|odd)(?:\\((\\d*)\\)|)(?=[^-]|$)","ig"),needsContext:/^[\x20\t\r\n\f]*[>+~]|:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\)|)(?=[^-]|$)/i},P={},Q=[],R={},S=[],B=function(a){a.sizzleFilter=!0;return a},z=function(a){return function(b){return"input"===b.nodeName.toLowerCase()&&b.type===a}},Z=function(a){return function(b){var e=b.nodeName.toLowerCase();return("input"===e||"button"===e)&&b.type===a}},x=function(a){var b=!1,e=r.createElement("div");try{b=a(e)}catch(c){}return b},
ja=x(function(a){a.innerHTML="<select></select>";a=typeof a.lastChild.getAttribute("multiple");return"boolean"!==a&&"string"!==a}),ka=x(function(a){a.id=y+0;a.innerHTML="<a name='"+y+"'></a><div name='"+y+"'></div>";k.insertBefore(a,k.firstChild);var b=r.getElementsByName&&r.getElementsByName(y).length===2+r.getElementsByName(y+0).length;s=!r.getElementById(y);k.removeChild(a);return b}),la=x(function(a){a.appendChild(r.createComment(""));return 0===a.getElementsByTagName("*").length}),ma=x(function(a){a.innerHTML=
"<a href='#'></a>";return a.firstChild&&"undefined"!==typeof a.firstChild.getAttribute&&"#"===a.firstChild.getAttribute("href")}),$=x(function(a){a.innerHTML="<div class='hidden e'></div><div class='hidden'></div>";if(!a.getElementsByClassName||0===a.getElementsByClassName("e").length)return!1;a.lastChild.className="e";return 1!==a.getElementsByClassName("e").length}),p=function(a,b,e,c){e=e||[];b=b||r;var d,g,l,f,h=b.nodeType;if(1!==h&&9!==h)return[];if(!a||"string"!==typeof a)return e;l=T(b);if(!l&&
!c&&(d=fa.exec(a)))if(f=d[1])if(9===h)if((g=b.getElementById(f))&&g.parentNode){if(g.id===f)return e.push(g),e}else return e;else{if(b.ownerDocument&&(g=b.ownerDocument.getElementById(f))&&na(b,g)&&g.id===f)return e.push(g),e}else{if(d[2])return I.apply(e,E.call(b.getElementsByTagName(a),0)),e;if((f=d[3])&&$&&b.getElementsByClassName)return I.apply(e,E.call(b.getElementsByClassName(f),0)),e}return U(a,b,e,c,l)},n=p.selectors={cacheLength:50,match:F,order:["ID","TAG"],attrHandle:{},createPseudo:B,
find:{ID:s?function(a,b,e){if("undefined"!==typeof b.getElementById&&!e)return(a=b.getElementById(a))&&a.parentNode?[a]:[]}:function(a,b,e){if("undefined"!==typeof b.getElementById&&!e)return(b=b.getElementById(a))?b.id===a||"undefined"!==typeof b.getAttributeNode&&b.getAttributeNode("id").value===a?[b]:K:[]},TAG:la?function(a,b){if("undefined"!==typeof b.getElementsByTagName)return b.getElementsByTagName(a)}:function(a,b){var e=b.getElementsByTagName(a);if("*"===a){for(var c,d=[],g=0;c=e[g];g++)1===
c.nodeType&&d.push(c);return d}return e}},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){a[1]=a[1].replace(J,"");a[3]=(a[4]||a[5]||"").replace(J,"");"~="===a[2]&&(a[3]=" "+a[3]+" ");return a.slice(0,4)},CHILD:function(a){a[1]=a[1].toLowerCase();"nth"===a[1]?(a[2]||p.error(a[0]),a[3]=+(a[3]?a[4]+(a[5]||1):2*("even"===a[2]||"odd"===a[2])),a[4]=+(a[6]+a[7]||"odd"===a[2])):a[2]&&p.error(a[0]);
return a},PSEUDO:function(a){var b,e=a[4];if(F.CHILD.test(a[0]))return null;e&&(b=Y.exec(e))&&b.pop()&&(a[0]=a[0].slice(0,b[0].length-e.length-1),e=b[0].slice(0,-1));a.splice(2,3,e||a[3]);return a}},filter:{ID:s?function(a){a=a.replace(J,"");return function(b){return b.getAttribute("id")===a}}:function(a){a=a.replace(J,"");return function(b){return(b="undefined"!==typeof b.getAttributeNode&&b.getAttributeNode("id"))&&b.value===a}},TAG:function(a){if("*"===a)return function(){return!0};a=a.replace(J,
"").toLowerCase();return function(b){return b.nodeName&&b.nodeName.toLowerCase()===a}},CLASS:function(a){var b=P[a];b||(b=P[a]=RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"),Q.push(a),Q.length>n.cacheLength&&delete P[Q.shift()]);return function(a){return b.test(a.className||"undefined"!==typeof a.getAttribute&&a.getAttribute("class")||"")}},ATTR:function(a,b,e){return b?function(c){c=p.attr(c,a);var d=c+"";if(null==c)return"!="===b;switch(b){case "=":return d===e;case "!=":return d!==
e;case "^=":return e&&0===d.indexOf(e);case "*=":return e&&-1<d.indexOf(e);case "$=":return e&&d.substr(d.length-e.length)===e;case "~=":return-1<(" "+d+" ").indexOf(e);case "|=":return d===e||d.substr(0,e.length+1)===e+"-"}}:function(b){return null!=p.attr(b,a)}},CHILD:function(a,b,e,c){if("nth"===a){var d=W++;return function(a){var b,A=0,g=a;if(1===e&&0===c)return!0;if((b=a.parentNode)&&(b[y]!==d||!a.sizset)){for(g=b.firstChild;g&&(1!==g.nodeType||(g.sizset=++A,g!==a));g=g.nextSibling);b[y]=d}a=
a.sizset-c;return 0===e?0===a:0===a%e&&0<=a/e}}return function(b){var e=b;switch(a){case "only":case "first":for(;e=e.previousSibling;)if(1===e.nodeType)return!1;if("first"===a)return!0;e=b;case "last":for(;e=e.nextSibling;)if(1===e.nodeType)return!1;return!0}}},PSEUDO:function(a,b,e,c){var d=n.pseudos[a]||n.pseudos[a.toLowerCase()];d||p.error("unsupported pseudo: "+a);return d.sizzleFilter?d(b,e,c):d}},pseudos:{not:B(function(a,b,e){var c=aa(a.replace(M,"$1"),b,e);return function(a){return!c(a)}}),
enabled:function(a){return!1===a.disabled},disabled:function(a){return!0===a.disabled},checked:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&!!a.checked||"option"===b&&!!a.selected},selected:function(a){a.parentNode&&a.parentNode.selectedIndex;return!0===a.selected},parent:function(a){return!n.pseudos.empty(a)},empty:function(a){var b;for(a=a.firstChild;a;){if("@"<a.nodeName||3===(b=a.nodeType)||4===b)return!1;a=a.nextSibling}return!0},contains:B(function(a){return function(b){return-1<
(b.textContent||b.innerText||V(b)).indexOf(a)}}),has:B(function(a){return function(b){return 0<p(a,b).length}}),header:function(a){return ha.test(a.nodeName)},text:function(a){var b,e;return"input"===a.nodeName.toLowerCase()&&"text"===(b=a.type)&&(null==(e=a.getAttribute("type"))||e.toLowerCase()===b)},radio:z("radio"),checkbox:z("checkbox"),file:z("file"),password:z("password"),image:z("image"),submit:Z("submit"),reset:Z("reset"),button:function(a){var b=a.nodeName.toLowerCase();return"input"===
b&&"button"===a.type||"button"===b},input:function(a){return ia.test(a.nodeName)},focus:function(a){var b=a.ownerDocument;return a===b.activeElement&&(!b.hasFocus||b.hasFocus())&&!(!a.type&&!a.href)},active:function(a){return a===a.ownerDocument.activeElement}},setFilters:{first:function(a,b,e){return e?a.slice(1):[a[0]]},last:function(a,b,e){b=a.pop();return e?a:[b]},even:function(a,b,e){b=[];e=e?1:0;for(var c=a.length;e<c;e+=2)b.push(a[e]);return b},odd:function(a,b,e){b=[];e=e?0:1;for(var c=a.length;e<
c;e+=2)b.push(a[e]);return b},lt:function(a,b,e){return e?a.slice(+b):a.slice(0,+b)},gt:function(a,b,e){return e?a.slice(0,+b+1):a.slice(+b+1)},eq:function(a,b,e){b=a.splice(+b,1);return e?a:b}}};n.setFilters.nth=n.setFilters.eq;n.filters=n.pseudos;ma||(n.attrHandle={href:function(a){return a.getAttribute("href",2)},type:function(a){return a.getAttribute("type")}});ka&&(n.order.push("NAME"),n.find.NAME=function(a,b){if("undefined"!==typeof b.getElementsByName)return b.getElementsByName(a)});$&&(n.order.splice(1,
0,"CLASS"),n.find.CLASS=function(a,b,e){if("undefined"!==typeof b.getElementsByClassName&&!e)return b.getElementsByClassName(a)});try{E.call(k.childNodes,0)[0].nodeType}catch(ra){E=function(a){for(var b,e=[];b=this[a];a++)e.push(b);return e}}var T=p.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1},na=p.contains=k.compareDocumentPosition?function(a,b){return!!(a.compareDocumentPosition(b)&16)}:k.contains?function(a,b){var e=9===a.nodeType?a.documentElement:
a,c=b.parentNode;return a===c||!(!c||1!==c.nodeType||!e.contains||!e.contains(c))}:function(a,b){for(;b=b.parentNode;)if(b===a)return!0;return!1},V=p.getText=function(a){var b,e="",c=0;if(b=a.nodeType)if(1===b||9===b||11===b){if("string"===typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)e+=V(a)}else{if(3===b||4===b)return a.nodeValue}else for(;b=a[c];c++)e+=V(b);return e};p.attr=function(a,b){var e;(e=T(a))||(b=b.toLowerCase());return n.attrHandle[b]?n.attrHandle[b](a):
ja||e?a.getAttribute(b):(e=a.getAttributeNode(b))?"boolean"===typeof a[b]?a[b]?b:null:e.specified?e.value:null:null};p.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};[0,0].sort(function(){return X=0});k.compareDocumentPosition?f=function(a,b){return a===b?(H=!0,0):(a.compareDocumentPosition&&b.compareDocumentPosition?a.compareDocumentPosition(b)&4:a.compareDocumentPosition)?-1:1}:(f=function(a,b){if(a===b)return H=!0,0;if(a.sourceIndex&&b.sourceIndex)return a.sourceIndex-
b.sourceIndex;var e,c,d=[],g=[];e=a.parentNode;c=b.parentNode;var f=e;if(e===c)return h(a,b);if(e){if(!c)return 1}else return-1;for(;f;)d.unshift(f),f=f.parentNode;for(f=c;f;)g.unshift(f),f=f.parentNode;e=d.length;c=g.length;for(f=0;f<e&&f<c;f++)if(d[f]!==g[f])return h(d[f],g[f]);return f===e?h(a,g[f],-1):h(d[f],b,1)},h=function(a,b,c){if(a===b)return c;for(a=a.nextSibling;a;){if(a===b)return-1;a=a.nextSibling}return 1});p.uniqueSort=function(a){var b,c=1;if(f&&(H=X,a.sort(f),H))for(;b=a[c];c++)b===
a[c-1]&&a.splice(c--,1);return a};var aa=p.compile=function(d,b,e){var g,f,h=R[d];if(h&&h.context===b)return h;var l,w=[];g=0;for(var m=Y.exec(d),u=!m.pop()&&!m.pop(),v=u&&d.match(N)||[""],k=n.preFilter,t=n.filter,s=!e&&b!==r;null!=(l=v[g])&&u;g++)for(w.push(h=[]),s&&(l=" "+l);l;){u=!1;if(m=L.exec(l))l=l.slice(m[0].length),u=h.push({part:m.pop().replace(M," "),captures:m});for(f in t)!(m=F[f].exec(l))||k[f]&&!(m=k[f](m,b,e))||(l=l.slice(m.shift().length),u=h.push({part:f,captures:m}));if(!u)break}u||
p.error(d);for(f=0;g=w[f];f++){h=w;l=f;m=b;u=e;k=v=void 0;for(t=0;v=g[t];t++)n.relative[v.part]?k=a(k,n.relative[v.part],m):(v.captures.push(m,u),k=c(k,n.filter[v.part].apply(null,v.captures)));h[l]=k}h=R[d]=function(a,b){for(var c,e=0;c=w[e];e++)if(c(a,b))return!0;return!1};h.context=b;h.runs=h.dirruns=0;S.push(d);S.length>n.cacheLength&&delete R[S.shift()];return h};p.matches=function(a,b){return p(a,null,null,b)};p.matchesSelector=function(a,b){return 0<p(b,null,null,[a]).length};var U=function(a,
b,c,f,h){a=a.replace(M,"$1");var k,l,w,m,u,v,s;m=a.match(N);w=a.match(ea);u=b.nodeType;if(F.POS.test(a)){k=a;var r,y,q,z,x;w=0;u=m.length;v=F.POS;s=RegExp("^"+v.source+"(?![\\x20\\t\\r\\n\\f])","i");for(var C=function(){for(var a=1,b=arguments.length-2;a<b;a++)arguments[a]===K&&(r[a]=K)};w<u;w++){v.exec("");k=m[w];h=[];a=0;for(q=f;r=v.exec(k);)if(x=v.lastIndex=r.index+r[0].length,x>a){l=k.slice(a,r.index);a=x;z=[b];L.test(l)&&(q&&(z=q),q=f);if(y=ga.test(l))l=l.slice(0,-5).replace(L,"$&*");1<r.length&&
r[0].replace(s,C);x=l;var B=r[1],H=r[2],D=void 0,G=n.setFilters[B.toLowerCase()];G||p.error(B);!x&&(D=q)||t(x||"*",z,D=[],q);q=0<D.length?G(D,H,y):[]}q?(h=h.concat(q),(l=k.slice(a))&&")"!==l?L.test(l)?t(l,h,c,f):p(l,b,c,f?f.concat(q):q):I.apply(c,h)):p(k,b,c,f)}return 1===u?c:p.uniqueSort(c)}if(f)k=E.call(f,0);else if(m&&1===m.length){if(1<w.length&&9===u&&!h&&(m=F.ID.exec(w[0]))){b=n.find.ID(m[1],b,h)[0];if(!b)return c;a=a.slice(w.shift().length)}l=(m=O.exec(w[0]))&&!m.index&&b.parentNode||b;s=w.pop();
u=s.split(":not")[0];f=0;for(w=n.order.length;f<w;f++)if(v=n.order[f],m=F[v].exec(u))if(k=n.find[v]((m[1]||"").replace(J,""),l,h),null!=k){u===s&&((a=a.slice(0,a.length-s.length)+u.replace(F[v],""))||I.apply(c,E.call(k,0)));break}}if(a)for(l=aa(a,b,h),g=l.dirruns++,null==k&&(k=n.find.TAG("*",O.test(a)&&b.parentNode||b)),f=0;m=k[f];f++)d=l.runs++,l(m,b)&&c.push(m);return c};if(r.querySelectorAll){var ba,oa=U,pa=/'|\\/g,qa=/\=[\x20\t\r\n\f]*([^'"\]]*)[\x20\t\r\n\f]*\]/g,q=[],D=[":active"],G=k.matchesSelector||
k.mozMatchesSelector||k.webkitMatchesSelector||k.oMatchesSelector||k.msMatchesSelector;x(function(a){a.innerHTML="<select><option selected></option></select>";a.querySelectorAll("[selected]").length||q.push("\\[[\\x20\\t\\r\\n\\f]*(?:checked|disabled|ismap|multiple|readonly|selected|value)");a.querySelectorAll(":checked").length||q.push(":checked")});x(function(a){a.innerHTML="<p test=''></p>";a.querySelectorAll("[test^='']").length&&q.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:\"\"|'')");a.innerHTML="<input type='hidden'>";
a.querySelectorAll(":enabled").length||q.push(":enabled",":disabled")});q=q.length&&RegExp(q.join("|"));U=function(a,b,c,d,f){if(!(d||f||q&&q.test(a)))if(9===b.nodeType)try{return I.apply(c,E.call(b.querySelectorAll(a),0)),c}catch(g){}else if(1===b.nodeType&&"object"!==b.nodeName.toLowerCase()){var h=b.getAttribute("id"),k=h||y,m=O.test(a)&&b.parentNode||b;h?k=k.replace(pa,"\\$&"):b.setAttribute("id",k);try{return I.apply(c,E.call(m.querySelectorAll(a.replace(N,"[id='"+k+"'] $&")),0)),c}catch(n){}finally{h||
b.removeAttribute("id")}}return oa(a,b,c,d,f)};G&&(x(function(a){ba=G.call(a,"div");try{G.call(a,"[test!='']:sizzle"),D.push(n.match.PSEUDO.source,n.match.POS.source,"!=")}catch(b){}}),D=RegExp(D.join("|")),p.matchesSelector=function(a,b){b=b.replace(qa,"='$1']");if(!(T(a)||D.test(b)||q&&q.test(b)))try{var c=G.call(a,b);if(c||ba||a.document&&11!==a.document.nodeType)return c}catch(d){}return 0<p(b,null,null,[a]).length})}C.ReadSpeaker.Sizzle=p})(window);
ReadSpeaker.lib.RSLib=function(){var C={core_pnum:function(){return/[\-+]?(?:\d*\.|)\d+(?:[eE][\-+]?\d+|)/.source},rposition:function(){return/^(top|right|bottom|left)$/},rmargin:function(){return/^margin/},rnumsplit:function(){return RegExp("^("+this.core_pnum+")(.*)$","i")},rnumnonpx:function(){return RegExp("^("+this.core_pnum+")(?!px)[a-z%]+$","i")},rmsPrefix:function(){return/^-ms-/},rdashAlpha:function(){return/-([\da-z])/gi}},K={_formatRet:function(a){return a.length?1==a.length?a[0].length&&
"object"===typeof a[0]&&!a[0].tagName?a[0][0]:a[0]:a:[]},get:function(a){return"#"===a?[]:"object"==typeof a?a:document.getElementById(a)||this._formatRet(window.ReadSpeaker.Sizzle(a))},findIn:function(a,c){"string"===typeof a&&(a=this.get(a));return this._formatRet(window.ReadSpeaker.Sizzle(c,a))},closest:function(a,c){var d=!1,g=null,f=null,h=a;"string"===typeof a&&(h=this.get(a));g=$rs.findIn(h.parentNode,c);if(g===h)return h;for(;!d&&h!==document.body;){f=h.parentNode;g=h.parentNode.parentNode;
if((g=$rs.findIn(g,c))&&g===f){d=!0;break}else if(g&&$rs.isArray(g)&&g.length)for(var h=0,s=g.length;h<s;h++)if(g[h]&&g[h]===f){d=!0;g=g[h];break}h=f}if(d)return g},getAttr:function(a,c){"string"===typeof a&&(a=this.get(a));if("style"===c)return a.style.cssText.toLowerCase()||void 0;if(a.getAttribute)return a.getAttribute(c);if(a[c])return a[c]},setAttr:function(a,c,d){"string"===typeof a&&(a=this.get(a));this.isArray(a)||(a=[a]);for(var g=0,f=a.length;g<f;g++)"style"===c?a[g].style.cssText=d:a[g].setAttribute?
a[g].setAttribute(c,d):a[g][c]=d;return d},regEvent:function(a,c,d){var g,f;"string"===typeof a&&(a=this.get(a));this.isArray(a)||(a=[a]);for(var h=0,s=a.length;h<s;h++)f=a[h].window?document.documentElement:a[h],g=this.getAttr(f,"data-rsevent-id")||"rs_"+Math.round(1E6*Math.random()),this.setAttr(f,"data-rsevent-id",g),t.push(g,c,d),t.store[g]&&t.store[g][c]&&1<t.store[g][c].length||_addEvent(a[h],c,t.dispatch)},unregEvent:function(a,c,d){if(a){var g;"string"===typeof a&&(a=this.get(a));this.isArray(a)||
(a=[a]);for(var f=0,h=a.length;f<h;f++)if(g=a[f].window?document.documentElement:a[f],g=this.getAttr(g,"data-rsevent-id"),d)(g=t.pop(g,c,d))||_removeEvent(a[f],c,t.dispatch);else if(_removeEvent(a[f],c,t.dispatch),g&&c){t.store[g][c]=void 0;try{delete t.store[g][c]}catch(s){}}}},fireEvent:function(){return!1},width:function(a){"string"===typeof a&&(a=this.get(a));return _getSize(a,"width")},height:function(a){"string"===typeof a&&(a=this.get(a));return _getSize(a,"height")},innerWidth:function(a){"string"===
typeof a&&(a=this.get(a));var c=parseFloat(_getCss(a,"border-left-width"))+parseFloat(_getCss(a,"border-right-width"));return _getSize(a,"width")-c},innerHeight:function(a){"string"===typeof a&&(a=this.get(a));var c=parseFloat(_getCss(a,"border-top-width"))+parseFloat(_getCss(a,"border-bottom-width"));return _getSize(a,"height")-c},outerWidth:function(a,c){"string"===typeof a&&(a=this.get(a));if(a&&a.style){var d=c?parseFloat(_getCss(a,"margin-left"))+parseFloat(_getCss(a,"margin-right")):0;return _getSize(a,
"width")+d}return null},outerHeight:function(a,c){"string"===typeof a&&(a=this.get(a));if(a&&a.style){var d=c?parseFloat(_getCss(a,"margin-top"))+parseFloat(_getCss(a,"margin-bottom")):0;return _getSize(a,"height")+d}return null},offsetParent:function(a){"string"===typeof a&&(a=this.get(a));for(var c=/absolute|relative|fixed/i;a!==document.body&&(a=a.parentNode,!a.style||!c.test(_getCss(a,"position"))););return a||document.body},offset:function(a){"string"===typeof a&&(a=this.get(a));var c=document.body,
d=document.defaultView||window,g=document.documentElement,f=document.createElement("div");if(a===document.body)return a=c.offsetTop,f=c.offsetLeft,/explorer/i.test(rspkr.c.data.browser.name)&&8>rspkr.c.data.browser.version||(a+=parseFloat(_getCss(c,"marginTop"))||0,f+=parseFloat(_getCss(c,"marginLeft"))||0),{top:a,left:f};f.style.paddingLeft=f.style.width="1px";c.appendChild(f);var h=2==f.offsetWidth;c.removeChild(f);var f=a.getBoundingClientRect(),s=g.clientTop||c.clientTop||0,r=g.clientLeft||c.clientLeft||
0,k=d.pageYOffset||h&&g.scrollTop||c.scrollTop,d=d.pageXOffset||h&&g.scrollLeft||c.scrollLeft;rspkr.basicMode&&a===c&&k&&!f.top&&(f.top=-k);rspkr.basicMode&&a===c&&d&&!f.left&&(f.left=-d);return{top:f.top+k-s,left:f.left+d-r}},absOffset:function(a){return this.offset(a)},position:function(a){"string"===typeof a&&this.get(a);return!1},scrollLeft:function(a,c){"string"===typeof a&&(a=this.get(a));return _scrollXY("scrollLeft","pageXOffset",a,c)},scrollTop:function(a,c){"string"===typeof a&&(a=this.get(a));
return _scrollXY("scrollTop","pageYOffset",a,c)},addClass:function(a,c){"string"===typeof a&&(a=this.get(a));this.isArray(a)||(a=[a]);for(var d,g=0,f=a.length;g<f;g++)d=_trim(a[g].className+" "+c).replace(/ {2,}/g," ").split(" "),a[g].className=d.join(" ")},removeClass:function(a,c){if(a){"string"===typeof a&&(a=this.get(a));this.isArray(a)||(a=[a]);for(var d,g=0,f=a.length;g<f;g++){d=_trim(c).replace(/ {2,}/g," ");newClassName=_trim(a[g].className);this.isArray(d)||(d=d.split(" "));for(var h=0,s=
d.length;h<s;h++)newClassName=newClassName.replace(RegExp("\\b"+d[h]+"\\b","gi"),"");a[g].className=_trim(newClassName).replace(/ {2,}/g," ")}}},hasClass:function(a,c){"string"===typeof a&&(a=this.get(a));if(!a||this.isArray(a)&&!a.length)return!1;for(var d=a.className.split(" "),g=0,f=d.length;g<f;g++)if(d[g]==c)return!0;return!1},css:function(a,c,d){"string"===typeof a&&(a=this.get(a));if("object"==typeof c||d){var g={};"string"===typeof c?g[_camelCase(c)]=d:g=c;for(var f in g)g.hasOwnProperty(f)&&
(a.style[_camelCase(f)]=g[f])}else return _getCss(a,_camelCase(c))},isVisible:function(a){for(;a!==document.body;){if("none"===this.css(a,"display"))return!1;a=a.parentNode}return!0},addStyleRule:function(a,c,d){d="string"==typeof d?document.styleSheets[d]||document.getElementById(d):d;d.addRule?d.addRule(a,c):d.sheet.insertRule&&d.sheet.insertRule(a+" {"+c+"}",d.sheet.cssRules.length)},isArray:function(a){return"[object Array]"===Object.prototype.toString.call(a)},rsid:function(a){if(""==this.getAttr(a,
"data-rsid")||void 0==this.getAttr(a,"data-rsid")){var c=ReadSpeaker.rsidCount++;this.setAttr(a,"data-rsid",c)}return this.getAttr(a,"data-rsid")},detach:function(a){return a.parentNode.removeChild(a)},convertEvent:function(a,c){a=a||window.event;var d=new ReadSpeaker.lib.Facade.RSEvent;d.pageX=a.pageX||a.clientX+$rs.scrollLeft(document);d.pageY=a.pageY||a.clientY+$rs.scrollTop(document);d.screenX=a.screenX;d.screenY=a.screenY;d.clientX=a.clientX;d.clientY=a.clientY;d.target=a.currentTarget||c;d.type=
a.type;d.keyCode=a.keyCode;d.targetTouches=a.targetTouches;d.originalEvent=a;return d},clone:function(a,c,d){return a.cloneNode(d||!1)},camel:function(a){return _camelCase(a)},remove:function(){return jQuery(elm).remove()},replaceWith:function(a,c){return _formatRet(jQuery(a).replaceWith(c))},focus:function(a,c){void 0!==c?this.focusIn(a,c):(a=this.get(a),this.isArray(a)&&0<a.length?a[0].focus?a[0].focus():a[0].setActive&&a[0].setActive():a.focus?a.focus():a.setActive&&a.setActive())},focusIn:function(a,
c){a=this.get(a);if(this.isArray(a)&&0<a.length)for(var d=0;d<a.length;d++)void 0!==c&&_addEvent(a[d],"focus",c);else void 0!==c&&_addEvent(a,"focus",c)},focusOut:function(a,c){a=this.get(a);if(this.isArray(a)&&0<a.length)for(var d=0;d<a.length;d++)void 0!==c&&_addEvent(a[d],"blur",c);else void 0!==c&&_addEvent(a,"blur",c)}},t=null;_getWindow=function(a){return null!=a&&a==a.window?a:9===a.nodeType?a.defaultView||a.parentWindow:!1};_camelCase=function(a){return a.replace(C.rmsPrefix(),"ms-").replace(C.rdashAlpha(),
_fcamelCase)};_fcamelCase=function(a,c){return(c+"").toUpperCase()};_trim=function(a){return a.replace(/^ +/,"").replace(/ +$/,"")};_getCss=window.getComputedStyle?function(a,c){return window.getComputedStyle(a,null)[_camelCase(c)]||!1}:function(a,c){var d,g,f=a.currentStyle&&a.currentStyle[c],h=a.style;null==f&&h&&h[c]&&(f=h[c]);if(C.rnumnonpx().test(f)&&!C.rposition().test(c)){d=h.left;if(g=a.runtimeStyle&&a.runtimeStyle.left)a.runtimeStyle.left=a.currentStyle.left;h.left="fontSize"===c?"1em":f;
f=h.pixelLeft+"px";h.left=d;g&&(a.runtimeStyle.left=g)}return""===f?"auto":f};_getSize=function(a,c){var d="width"==c?"Width":"Height";if(a!==window&&a!==document){d=a["offset"+d];if(isNaN(d)||!d)d=_getCss(a,c);isNaN(d);return parseInt(d)}try{if(a===window)return window["inner"+d]||document.documentElement["client"+d]||document.body["client"+d];if(a===document)return document.body["client"+d]}catch(g){return rspkr.log("[RSLib._getSize] Error: "+g.message,3),0}};_scrollXY=function(a,c,d,g){var f=/X/.test(c),
h=_getWindow(d);if(void 0===g)return h?c in h?h[c]:h.document.documentElement[a]||document&&document.body&&document.body[a]:d[a];h?h.scrollTo(f?$rs.scrollLeft(h):g,f?g:$rs.scrollTop(h)):d[a]=g};_addEvent=document.addEventListener?function(a,c,d){a.addEventListener&&a.addEventListener(c,d,!1)}:function(a,c,d){a.attachEvent&&a.attachEvent("on"+c,function(c){d(c,a)})};_removeEvent=document.removeEventListener?function(a,c,d){a.removeEventListener&&a.removeEventListener(c,d,!1)}:function(a,c,d){a.detachEvent&&
a.detachEvent("on"+c,d)};return{meta:{revision:"3975"},init:function(){window.ReadSpeaker.Sizzle?(t=ReadSpeaker.lib.Facade.eq,ReadSpeaker.lib.Facade.adapterInit(K),ReadSpeaker.log("[rspkr.l.RSLib] Initialized."),rspkr.Common.dispatchEvent("onAdapterReady")):ReadSpeaker.log("[rspkr.l.RSLib] Error, Sizzle unavailable.",3)}}}();
