ReadSpeaker.ui=function(){var a=null,f=[],p=[],y=!1,t=function(g){g=g||window.event;g.returnValue=!1;if(g=g.originalEvent)g.cancelBubble=!0,g.returnValue=!1;g&&g.preventDefault&&g.preventDefault();g&&g.stopPropagation&&g.stopPropagation()},n=function(){rspkr.log("[rspkr.ui] Attempting to add click events.");var g=$rs.get("."+rspkr.ui.rsbtnClass+" .rsbtn_play"),a=null;$rs.isArray(g)||(g=[g]);for(var c=0,b=g.length;c<b;c++)if($rs.unregEvent(g[c],"click",ReadSpeakerDefer.clickhandler),a=g[c]?$rs.getAttr(g[c],
"data-rsevent-id"):"_bogus_",rspkr.l.f.eq.store[a]&&rspkr.l.f.eq.store[a].click)rspkr.log("[rspkr.ui] Click event already existed on "+g[c],2);else{$rs.regEvent(g[c],"click",function(h){t(h);window.readpage(this)});rspkr.ui.addFocusHandler(g[c],!0,g[c].parentNode);rspkr.log("[rspkr.ui] Added click event to: "+g[c],1);try{$rs.getAttr(g[c],"role")||$rs.setAttr(g[c],"role","button")}catch(f){rspkr.log("[rspkr.ui] Could not add role attribute.",2)}}},A=function(){rspkr.log("[rspkr.ui] Initiating global callbacks");
rspkr.ui.rsbtnClass=rspkr.cfg.item("ui.rsbtnClass")||"rsbtn";window.readpage=function(g,a){if(rspkr.ui.initrun){if(/ios|ipad|iphone|ipod|android|windows phone/i.test(window.navigator.userAgent)){var c=window.rspkr;c.audio=new Audio;c.audio.play();c.audio.pause()}rspkr.ui.showPlayer(g,a)}};window.rshlexit=function(g){rspkr.HL.chunking&&rspkr.HL.chunking.destroy();void 0!==g&&"false"!==g||a.stop();setTimeout(function(){rspkr.c.dispatchEvent("onAfterSyncExit",window)},1E3)};window.rshlinit=r().sync.init;
window.rshlsetContent=r().sync.setContent;window.rshlsetId=r().sync.setId;window.rshlsync=function(g,a){for(var c=g.split(","),b=a.split(","),h=0,q=g.length;h<q;h++)r().sync.execute(c[h],b[h])};window.rshlcontinue=function(){function g(h){if(!rspkr.HL.chunking.entracte.src){h=encodeURIComponent(decodeURIComponent(rs.cfg.getPhrase(h)));var a={noads:1},c;for(c in rspkr.c.data.params)rspkr.c.data.params.hasOwnProperty(c)&&(a[c]=rspkr.c.data.params[c]);c=rspkr.Common.data.selectedText;var b=rspkr.Common.data.selectedHTML;
rspkr.Common.data.selectedText=h;rspkr.Common.data.selectedHTML="";a.text=h;a.output="audio";h=rspkr.c.buildReadSpeakerCall(a);rspkr.HL.chunking.entracte.src=h;rspkr.Common.data.selectedText=c;rspkr.Common.data.selectedHTML=b}rspkr.HL.chunking.entracte.volume=parseFloat((rspkr.st.get("hlvol")||100)/100);rspkr.HL.chunking.entracte.play()}if(rspkr.HL.chunking){rspkr.log("[rspkr.ui.rshlcontinue]");rspkr.HL.chunking.chunkEnded=!0;var a=$rs.get("#sync"+rspkr.HL.html5.synclist[rspkr.HL.html5.synclist.length-
1][2]);$rs.isArray(a)&&!a.length?(a=0,document.body&&document.body.scrollTop?a=document.body.scrollTop:document.documentElement&&document.documentElement.scrollTop?a=document.documentElement.scrollTop:window.pageYOffset&&(a=window.pageYOffset),a={left:rs.ui.viewport.width/2,top:rs.ui.viewport.height/2+a}):a=$rs.offset(a);if(rspkr.HL.chunking.continueHref){var c=rspkr.cfg.item("cb.chunking.pause",void 0,!0);if(-1==rspkr.HL.chunking.continueTime)if(rspkr.log("[rspkr.ui.rshlcontinue] Waiting for user interaction"),
rs.ui.getActivePlayer().pause(),$rs.addClass(rspkr.ui.getActivePlayer().getContainer(),"rsautopaused"),g("chunkcontinue"),c&&"function"==typeof c)rspkr.log("[rspkr.ui.rshlcontinue] Running custom callback",3),c();else{rspkr.log("[rspkr.ui.rshlcontinue] Showing default continue button");c=document.createElement("div");c.innerHTML=rspkr.cfg.item("ui.popupbutton").join("");$rs.addClass(c,rspkr.ui.rsbtnClass+" rspopup rsresume");var b=$rs.findIn(c,"a");b.removeAttribute("href");$rs.regEvent(b,"click",
function(){rspkr.c.dispatchEvent("onChunkResume",window)});$rs.findIn(b,".rsbtn_text").innerHTML="<span>"+rs.cfg.getPhrase("chunkbutton")+"</span>";document.body.appendChild(c);c.style.display="block";a.left+=15;b=a.left+$rs.width(c)-$rs.width(window);0<b&&(a.left-=b);c.style.left=a.left+"px";c.style.top=a.top+15+"px"}else 0==rspkr.HL.chunking.continueTime?(rspkr.log("[rspkr.ui.rshlcontinue] Autoplay"),rspkr.c.dispatchEvent("onChunkResume",window)):isNaN(rspkr.HL.chunking.continueTime)?rspkr.log("[rshlcontinue] Invalid time parameter!",
3):(rspkr.log("[rspkr.ui.rshlcontinue] Autoplay with "+rspkr.HL.chunking.continueTime+" seconds delay"),5<=rspkr.HL.chunking.continueTime&&g("chunkwait"),c&&"function"==typeof c&&c(rspkr.HL.chunking.continueTime),rspkr.HL.chunking.stall=!0,setTimeout(function(){rspkr.HL.chunking.stall=!1},1E3*rspkr.HL.chunking.continueTime),rspkr.HL.chunking.timer=setTimeout(function(){rspkr.c.dispatchEvent("onChunkResume",window)},1E3*rspkr.HL.chunking.continueTime))}else rspkr.log("[rshlcontinue] No continue href found!")}};
var g=rspkr.c.data.browser;g&&(/iphone|ipad|ios|android|windows phone/i.test(g.OS)||"android"==g.name.toLowerCase())?($rs.regEvent(document.body,"touchstart",function(g){rspkr.ui.setPointerPos(g);return!0}),$rs.regEvent(document.body,"touchend",function(g){rspkr.ui.setPointerPos(g);rspkr.c.data.setSelectedText(g);return!0}),$rs.regEvent(document,"selectionchange",function(g){rspkr.c.data.setSelectedText(g);return!0})):($rs.regEvent(document.body,"mousedown",function(g){rspkr.ui.setPointerPos(g);return!0}),
$rs.regEvent(document.body,"mouseup",function(a){"opera"===g.name.toLowerCase()?setTimeout(function(){rspkr.c.data.setSelectedText(a)},50):rspkr.c.data.setSelectedText(a);return!0}),$rs.regEvent(window,"mouseup",function(a){"opera"===g.name.toLowerCase()?setTimeout(function(){rspkr.c.data.setSelectedText(a)},50):rspkr.c.data.setSelectedText(a);return!0}),$rs.regEvent(document.body,"keydown",rspkr.ui.setPointerPos),$rs.regEvent(document.body,"keyup",function(g){rspkr.c.data.setSelectedText(g);return!0}))},
w=function(){document.removeEventListener?document.removeEventListener("click",window.ReadSpeakerDefer.clickhandler,!1):document.detachEvent&&document.detachEvent("onclick",window.ReadSpeakerDefer.clickhandler);if(ReadSpeakerDefer.deferred){var g=ReadSpeakerDefer.deferred,a=null;if("a"!=g.tagName.toLowerCase()){for(a=g;"body"!=a.tagName.toLowerCase()&&(a=a.parentNode,"a"!=a.tagName.toLowerCase()););g=a}ReadSpeakerDefer.isRSLink(g)&&(rspkr.log("[rspkr.ui] Activating deferred element: "+g),$rs.removeClass(g.parentNode,
"rsdeferred"),rspkr.ui.showPlayer(g));ReadSpeakerDefer.deferred=null}},u=null,e=function(){u&&$rs.isVisible(u)&&(rspkr.log("[rspkr.ui.updateFocus] "+u.outerHTML),v(u))},v=function(g){$rs.focus&&"function"==typeof $rs.focus&&g&&$rs.focus(g)},c=function(g){if("iconon"==rspkr.st.get("hlicon")&&!y){var a=p.push(new l)-1;p[a].id=a;p[a].show(g);y=!0}},b=function(){"iconon"==rspkr.st.get("hlicon")&&y&&(p.pop().hide(),y=!1)},l=function(){var a=0,c=0,b=null,f=52,e=null,h=null,q=null,l=function(a){a=a||b;$rs.addClass(a,
rspkr.ui.rsbtnClass+" rspopup");rspkr.cfg.item("general.useCompactPopupButton")&&$rs.addClass(a,"rscompact")},F=function(a){$rs.unregEvent(b,"mouseout",k);window.clearTimeout(e);var g,c=b.clientWidth+10,f;h=rspkr.ui.showPlayer(q,b,!0);f=h.getWidth();g=parseInt($rs.offset(b).left);(g=rspkr.ui.viewport.width+$rs.scrollLeft(document)-g)<f&&(g=parseInt($rs.css(b,"left"))-(f-(c-10)),$rs.css(b,"left",g+"px"));y=!1;$rs.unregEvent(q,"click",F);$rs.regEvent(q,"click",function(a){t(a);return h.restart()});
t(a);return!1},k=function(){e||(e=window.setTimeout(function(){r()},rspkr.cfg.item("general.popupCloseTime")||2E3))},m=function(){e&&(window.clearTimeout(e),e=null)},n=function(a,g){var h=document.body.getBoundingClientRect();$rs.css(b,{top:g-h.top+"px",left:a-h.left+"px",width:f+"px"})},r=function(){$rs.css(b,{display:"none",top:0,left:0});m();p.splice(null,1);y=!1;b.parentElement.removeChild(b)},x=rspkr.c.findFirstRSButton(),b=document.createElement("div");b.id=rspkr.getID();b.innerHTML=rspkr.cfg.item("ui.popupbutton").join("");
l();q=$rs.findIn(b,".rsbtn_play");$rs.setAttr(q,"href",x?$rs.getAttr(x,"href"):null);(x=rspkr.cfg.item("general.popupHref"))&&$rs.setAttr(q,"href",x);var x=$rs.getAttr(q,"href").match(/lang=([^&;]*)/i).pop(),B=$rs.findIn($rs.get(b),".rsbtn_play span.rsbtn_text span");B&&(B.textContent=B.innerText=rspkr.cfg.getPhrase("listen",x,"en_us"));$rs.setAttr(q,"title",rspkr.cfg.getPhrase("listentoselectedtext",x,"en_us"));$rs.regEvent(q,"click",F);document.body.appendChild(b);return{setPos:n,show:function(h){m(h);
if(h&&"none"==$rs.css(b,"display")){var q=b.cloneNode(!0);q.id=rspkr.getID();$rs.css(q,{display:"block",position:"absolute",top:0,left:0});document.body.appendChild(q);f=$rs.outerWidth(q)+3;document.body.removeChild(q);q=h.clientX||h.pageX||rspkr.ui.pointerX;h=h.clientY||h.pageY||rspkr.ui.pointerY;c=h>rspkr.ui.pointerY?h-$rs.scrollTop(document)+36>rspkr.ui.viewport.height-46?h-66:h+30:10>h-$rs.scrollTop(document)-66?h+30:h-51;a=10>q-$rs.scrollLeft(document)?q+10:q-$rs.scrollLeft(document)>rspkr.ui.viewport.width-
(f+10)?rspkr.ui.viewport.width+$rs.scrollLeft(document)-(f+10):q+0;n(a,c)}$rs.regEvent(b,"mouseout",k);$rs.regEvent(b,"mouseover",m);k(null);l();$rs.css(b,"display","block")},hide:r,id:null}},k={update:function(g,c,b){"hlspeed"===g&&c!==b&&(g=g.replace("hl",""),rspkr.c.converter[g]&&"function"==typeof rspkr.c.converter[g]&&(c=rspkr.c.converter[g](c)),rspkr.c.data[g]=c,a&&a.stop(),rspkr.pl.releaseAdapter())}},m=function(a,c,b,f,e,h){$rs.css(a,"background-color","rgb("+c+","+b+","+f+")");f<e?(f+=10,
window.setTimeout(function(){m(a,c,b,f,e,h)},50)):h&&"function"===typeof h&&h.apply(a,[])},r=function(){return rspkr.XP?rspkr.XP:rspkr.HL};_expand=function(a){"string"==typeof a&&(a=$rs.get(a));$rs.isArray(a)||(a=[a]);for(var c=0;c<a.length;c++)rspkr.ui.Player(a[c]).show(!0)};_animate=function(){var a=rs.cfg.item("ui.animate");if(a){var c,b=15,f=500;"object"==typeof a?(a.id&&(c=$rs.get(a.id)),a.count&&(b=a.count),a.interval&&(f=a.interval)):"string"===typeof a&&(c=$rs.get(a));if("boolean"===typeof a&&
a||$rs.isArray(c)&&0==c.length||!c)c=$rs.get("."+rs.ui.rsbtnClass);$rs.isArray(c)||(c=[c]);var e=b,h=setInterval(function(){0==e&&($rs.removeClass(c,"rsanimate"),clearInterval(h));1==e--%2?$rs.addClass(c,"rsanimate"):$rs.removeClass(c,"rsanimate")},f)}};return{meta:{revision:"3975"},initrun:!1,init:function(){var a=rspkr.Common.addEvent;a("onAfterModsLoaded",A);a("onReady",n);a("onReady",w);a("onReady",_animate);a("onSelectedText",c);a("onDeselectedText",b);a("onSettingsChanged",k.update);a("onAfterSyncInit",
e);this.initrun=!0;rspkr.Common.dispatchEvent("onUIInitialized");rspkr.log("[rspkr.ui] Initialized!")},addFocusHandler:function(a,c,b){var f=c,e=b,e=e||a;void 0===f&&(f=!0);$rs.focusIn&&"function"==typeof $rs.focusIn&&($rs.focusIn(a,function(){$rs.addClass(e,"rsfocus");!0===f&&(u=a);rspkr.Common.dispatchEvent("onFocusIn",window,[a,e])}),$rs.focusOut(a,function(){$rs.removeClass(e,"rsfocus");rspkr.Common.dispatchEvent("onFocusOut",window,[a,e])}))},focus:function(a){v(a)},updateFocus:function(){e()},
showOverlay:function(c,b){var f=c,e;e=b||a.getContainer();var l=$rs.findIn(e,".rsbtn_status");0===l.length&&(l=document.createElement("span"),l.className="rsbtn_status_overlay",l.innerHTML='<span class="rsbtn_status"></span>',$rs.findIn(e,".rsbtn_exp").appendChild(l),l=$rs.findIn(e,".rsbtn_status"));$rs.css($rs.findIn(e,".rsbtn_status_overlay"),"display","block");if("nosound"===f)f='<a class="rsbtn_nosound">'+rspkr.cfg.getPhrase("nosound")+"</a>",l.innerHTML=f,(f=$rs.findIn(e,".rsbtn_nosound"))&&
$rs.regEvent(f,"click",function(){return a.nosound()});else if("loaderror"===f){var f=rspkr.c.data.getSaveData("link"),h=document.createElement("a");h.className="rsbtn_loaderror";h.innerHTML="[?]";h.href=f;$rs.regEvent(h,"click",function(a){rspkr.ui.Lightbox.show("<iframe src='"+h.href+"' style='height:100%'></iframe>",null,!1,null,300);t(a)});l.innerHTML=rspkr.cfg.getPhrase("loaderror")||"An error has occurred, try again";l.appendChild(h)}else l.innerHTML=f},settings:k,rsbtnClass:"",addClickEvents:function(){n()},
initGlobalCallbacks:function(){A()},showPopupIcon:function(a){c(a)},processDeferred:function(){w()},showPlayer:function(c,b,e){var l;a:{var k=e;rspkr.log("[rspkr.ui.showPlayer]");k=k||!1;if("string"==typeof c)b:{e=$rs.get("a");for(var h=0,q=e.length;h<q;h++)if(e[h].href&&e[h].href==c){e=e[h];break b}e=!1}else e=c;e=(h=e)?$rs.closest(h,".rsexpanded"):void 0;e=$rs.hasClass(e,"pre-expanded")?void 0:e;q=rspkr.HL.chunking?rspkr.HL.chunking.currentChunkNumber:1;if(e&&!$rs.isArray(e)&&rspkr.ui.getActivePlayer()&&
1==q&&rspkr.ui.getActivePlayer().getContainer()==e)rspkr.log("Player already active, calling Player.restart() instead"),rspkr.ui.getActivePlayer().restart(),l=void 0;else{rspkr.HL.chunking&&rspkr.HL.chunking.destroy();rspkr.HL.chunking&&rspkr.HL.chunking.html5support&&(rspkr.HL.chunking.entracte=new Audio,/ios|ipad|iphone|ipod|android|windows phone/i.test(window.navigator.userAgent)&&(rspkr.HL.chunking.entracte.play(),rspkr.HL.chunking.entracte.pause()));rspkr.c.dispatchEvent("onBeforeParamsSet",
window,[h]);e="string"==typeof c?c:$rs.getAttr(h,"href");q=null;"string"==typeof c&&(c=e.match(/readid=[^&]+/gi),q=e.match(/readclass=[^&]+/gi),c&&0<c.length&&rspkr.HL.Restore.Storage.readId.push(c[0].replace("readid=","").split(",")),q&&0<q.length&&rspkr.HL.Restore.Storage.readClass.push(q[0].replace("readclass=","").split(",")));rspkr.c.data.selectedHTML="";rspkr.c.data.setParams(e);void 0!==$rs.getAttr(h,"data-target")&&null!==$rs.getAttr(h,"data-target")&&(c=$rs.getAttr(h,"data-target"),c=$rs.get(c),
"object"===typeof c&&(b=c));b&&!k?(q=$rs.get(b),$rs.addClass(q,rspkr.ui.rsbtnClass+" rsfloating"),rspkr.basicMode&&($rs.removeClass(q,"rshidden"),$rs.addClass(q,rspkr.ui.rsbtnClass+" rsvisible"))):q=$rs.closest(h,"div."+rspkr.ui.rsbtnClass);if(!0===rspkr.cfg.item("survey.allowed"))if(b=rspkr.c.cookie,k=rspkr.cfg.item("survey.cookieName")||"rspkrsurvey",c=rspkr.cfg.item("survey.cookieLifetime")||15552E6,h=rspkr.c.data.params,"1"===b.readKey(k,"nmbrdisplays")){rspkr.ui.Lightbox.show(rspkr.cfg.item("survey.url")+
"?customerid="+h.customerid+"&lang="+h.lang,rspkr.st.r().replaceTokens(rspkr.cfg.item("ui.survey.buttons").join(),{rsSURVEY_BUTTON_CLOSErs:rspkr.cfg.getPhrase("close")}),!0,function(){$rs.regEvent($rs.get("#rssurvey_button_close"),"click",rspkr.u.Lightbox.hide)},500);rspkr.log(b.updateKey(k,"nmbrdisplays","displayed",c),4);l=void 0;break a}else void 0===b.readKey(k,"nmbrdisplays")&&rspkr.log(b.updateKey(k,"nmbrdisplays","1",c),4);b:{b=q;for(l in f)if(f[l]&&f[l].getContainer&&f[l].getContainer()==
b){l=f[l];break b}l=new rspkr.ui.Player(b);f.push(l)}if(a&&a!=l||a&&e!==a.getHref())a.close(!0),rspkr.c.dispatchEvent("onUIClosePlayer",a.getContainer(),[0<rspkr.c.data.selectedText.length?"textsel":"nosel"]);b=(b=a)?b.getID():null;rspkr.c.dispatchEvent("onUIShowPlayer",window,[b,l.getID()]);l.setHref(e);a=l;l.show();l=a}}return l},expand:function(a){_expand(a)},pointerX:0,pointerY:0,setPointerPos:function(a){a.pageX&&(rspkr.ui.pointerX=a.pageX);a.pageY&&(rspkr.ui.pointerY=a.pageY);a.originalEvent&&
a.originalEvent.touches&&a.originalEvent.touches[0]&&a.originalEvent.touches[0].pageX&&(rspkr.ui.pointerX=a.originalEvent.touches[0].pageX);a.originalEvent&&a.originalEvent.touches&&a.originalEvent.touches[0]&&a.originalEvent.touches[0].pageY&&(rspkr.ui.pointerY=a.originalEvent.touches[0].pageY);return!0},viewport:{width:$rs.width(window),height:$rs.height(window)},popups:p,hl:function(a,c){window.setTimeout(function(){m(a,255,255,100,255,c)},200)},scroll:{INTERVAL:null,STEPS:25,scrollToElm:function(a){$rs.isVisible(a)&&
this.initScroll(a)},scrollToAnchor:function(a){for(var c=$rs.get("a"),b=null,e=0;e<c.length;e++){var f=c[e];if(f.name&&f.name==a){b=f;break}}this.initScroll(b)},initScroll:function(a){if(a){for(var c=a.offsetTop,b=a;b.offsetParent&&b.offsetParent!=document.body;)b=b.offsetParent,c+=b.offsetTop;c-=50;rs.cfg.item("ui.autoscrollOffset")&&!isNaN(rs.cfg.item("ui.autoscrollOffset"))&&(c-=rs.cfg.item("ui.autoscrollOffset"));clearInterval(rspkr.u.scroll.INTERVAL);var b=rspkr.u.scroll.getCurrentYPos(),e=parseInt((c-
b)/rspkr.u.scroll.STEPS);rspkr.u.scroll.INTERVAL=setInterval(function(){rspkr.u.scroll.scrollWindow(e,c,a)},10)}else document.location.hash=a},getCurrentYPos:function(){return document.body&&document.body.scrollTop?document.body.scrollTop:document.documentElement&&document.documentElement.scrollTop?document.documentElement.scrollTop:window.pageYOffset?window.pageYOffset:0},scrollWindow:function(a,c,b){var e=rspkr.u.scroll.getCurrentYPos(),f=e<c;window.scrollTo(0,e+a);a=rspkr.u.scroll.getCurrentYPos();
if(f!=a<c||e==a)window.scrollTo(0,c),clearInterval(rspkr.u.scroll.INTERVAL),"string"==typeof b&&(location.hash=b)}},activePlayer:a,getActivePlayer:function(){return a}}}();
ReadSpeaker.ui.Slider=function(){var a=this,f={handleClass:"",width:0,height:0,left:0,top:0,steps:-1,stepsize:-1,dir:"h",initval:-1,drop:null,start:null,dragging:null,click:null,labelDragHandle:"",labelStart:"",labelEnd:"",nudge:1},p={rsid:void 0,parent:void 0,ref:void 0},y=void 0,t=void 0,n=void 0,A=void 0,w=void 0,u=!1,e=0,v=function(a){a=a||window.event;a.returnValue=!1;if(a=a.originalEvent)a.cancelBubble=!0,a.returnValue=!1;a&&a.preventDefault&&a.preventDefault();a&&a.stopPropagation&&a.stopPropagation()};
this.initElement=function(a){if(!u){"string"==typeof a&&(a=document.getElementById(a));a.innerHTML+='<a href="javascript:void(0);" role="slider" class="keyLink" style="display:block; border:0;">&#160;</a>';var b=a.getElementsByTagName("a"),b=b[b.length-1],l=-1<f.steps?f.steps:100;b.relatedElement=a;$rs.setAttr(b,"title",f.labelDragHandle);try{$rs.setAttr(b,"aria-label",f.labelDragHandle),$rs.setAttr(b,"aria-orientation","h"==f.dir?"horizontal":"vertical"),$rs.setAttr(b,"aria-valuemin",0),$rs.setAttr(b,
"aria-valuemax",l),$rs.setAttr(b,"aria-valuenow",f.initval||0)}catch(k){}e=f.initval;$rs.regEvent(a,"mousedown",this.startDragMouse);$rs.regEvent(b,"click",function(a){v(a)});$rs.regEvent(b,"keyup",this.startDragKeys);$rs.regEvent(b,"dragstart",function(a){v(a)});$rs.regEvent(a,"touchstart",this.touchStart);$rs.regEvent(p.parent,"mousedown",this.mouseClick)}};this.mouseClick=function(c){if(!u&&!$rs.hasClass(p.ref,"dragged")){var b=a.findPos(c.target),e=c.clientX-(b.left-f.left);c=c.clientY-(b.top-
f.top);n=b.left;A=b.top;b=a.getCurrentVal({left:e,top:c});"function"==typeof f.click&&f.click(b,p);return!1}};this.findPos=function(a){var b=curTop=0;if(a.offsetParent){do b+=a.offsetLeft,curTop+=a.offsetTop;while(a=a.offsetParent);return{left:b,top:curTop}}};this.startDragMouse=function(c){rspkr.log("[rspkr.ui.Slider] startDragMouse");if(!u){a.startDrag(this);var b=c||window.event;y=b.clientX;t=b.clientY;$rs.regEvent(document.body,"mousemove",a.dragMouse);$rs.regEvent(document.body,"mouseup",a.releaseElement)}v(c);
return!1};this.startDragKeys=function(c){rspkr.log("[rspkr.ui.Slider] startDragKeys "+(c||window.event).keyCode);a.startDrag(this.relatedElement);$rs.regEvent(document.body,"keydown",a.dragKeys);$rs.regEvent(document.body,"keypress",a.switchKeyEvents);$rs.addClass(this.relatedElement,"rskeycontrolled");v(c)};this.touchStart=function(c){c=c.originalEvent;rspkr.log("[rspkr.ui.Slider] touchStart");u||(a.startDrag(c.target),y=c.touches[0].pageX,t=c.touches[0].pageY,$rs.regEvent(c.target,"touchmove",a.touchMove),
$rs.regEvent(c.target,"touchend",a.releaseElement));return!1};this.startDrag=function(c){rspkr.log("[rspkr.ui.Slider] startDrag");w&&a.releaseElement();n=c.offsetLeft;A=c.offsetTop;w=c;$rs.addClass(w,"dragged");"function"==typeof f.start&&f.start(p)};this.dragMouse=function(c){c=c||window.event;a.setPosition(c.clientX-y,c.clientY-t);a.valueChanged=!0;return!1};this.touchMove=function(c){c=c.originalEvent?c.originalEvent:c;v(c);a.setPosition(c.touches[0].pageX-y,c.touches[0].pageY-t);a.valueChanged=
!0;return!1};this.dragKeys=function(c){switch((c||window.event).keyCode){case 37:case 63234:a.valueChanged=!0;e-=f.nudge;break;case 38:case 63232:a.valueChanged=!0;e+=f.nudge;break;case 39:case 63235:a.valueChanged=!0;e+=f.nudge;break;case 40:case 63233:a.valueChanged=!0;e-=f.nudge;break;case 13:case 27:return a.releaseElement(),!1;case 9:return a.releaseElement(),!0;default:return rspkr.log("[rspkr.ui.Slider] return TRUE"),!0}!0===a.valueChanged&&(rspkr.c.dispatchEvent("onUISliderMove"),"function"==
typeof f.dragging&&f.dragging(a.getCurrentVal({skipValueCalculation:!0}),p));v(c);rspkr.log("[rspkr.ui.Slider] ready to return!");return!1};this.setPosition=function(c,b){var e,k=!1;e=c;var m=n,r=f.left,g=f.width,z="left";"v"==f.dir&&(e=b,m=A,r=f.top,g=f.height,z="top");e=m+e;-1<f.stepsize&&((e+r)%f.stepsize?e=f.stepsize*Math.ceil(e/f.stepsize)+r:k=!0);e>g+r?e=g+r:e<r&&(e=r);k||(w.style[z]=e+"px","function"==typeof f.dragging&&f.dragging(a.getCurrentVal(),p))};this.switchKeyEvents=function(){$rs.unregEvent(document.body,
"keydown",a.dragKeys);$rs.unregEvent(document.body,"keypress",a.switchKeyEvents);$rs.regEvent(document.body,"keypress",a.dragKeys)};this.releaseElement=function(){rspkr.log("[rspkr.ui.Slider] releaseElement");$rs.unregEvent(document.body,"mousemove",a.dragMouse);$rs.unregEvent(document.body,"mouseup",a.releaseElement);$rs.unregEvent(document.body,"keypress",a.dragKeys);$rs.unregEvent(document.body,"keypress",a.switchKeyEvents);$rs.unregEvent(document.body,"keydown",a.dragKeys);$rs.unregEvent(w,"touchmove",
a.touchMove);$rs.unregEvent(w,"touchend",a.releaseElement);$rs.removeClass(w,"dragged");$rs.removeClass(w,"rskeycontrolled");$rs.removeClass(w,"rsmousecontrolled");var c=a.getCurrentVal();w=null;"function"==typeof f.drop&&!0===a.valueChanged&&f.drop(c,p);a.valueChanged=!1;rs.ui.getActivePlayer()&&rs.ui.getActivePlayer().setProgress();return!1};this.getCurrentVal=function(a){var b,l=f.width;b="left";var k=f.left;"v"==f.dir&&(l=f.height,b="top",k=f.top);var m=-1<f.steps?f.steps:100,l=-1<f.stepsize?
f.stepsize:l/m;a=a?a[b]:$rs.css(p.ref,b).replace(/px/i,"");pos=Math.round(a)-k;b=Math.round(pos/l);"v"==f.dir&&(b=m-b);rspkr.log("[rspkr.ui.Slider] currentval: "+b);return a&&a.skipValueCalculation||isNaN(b)?e=Math.max(Math.min(e,m),0):e=b};return{init:function(c,b){"string"==typeof c&&(c=document.getElementById(c));if(c){var e=c.id||"data-readspeaker-slider-id-"+Math.floor(2E4*Math.random());c.setAttribute&&c.setAttribute("data-readspeaker-slider-id-","data-readspeaker-slider-parent-"+e);var k={width:function(){return $rs.width(c)},
height:function(){return $rs.height(c)}};if("object"==typeof b)for(var m in b)b.hasOwnProperty(m)&&void 0!==f[m]&&(f[m]=b[m]);m=!1;var n;"rsbtn_volume_slider"===c.className&&"jquery"===rspkr.l.f.currentLib()&&1.5>parseFloat(jQuery.fn.jquery)&&(n=c.parentNode.style.display,c.parentNode.style.display="block",m=!0);f.width=k.width();f.height=k.height();m&&(c.parentNode.style.display=n);-1<f.steps&&(f.stepsize=("h"==f.dir?f.width:f.height)/f.steps);k=document.createElement("span");k.setAttribute("data-readspeaker-slider-id-",
e);k.className=f.handleClass||"rsbtn_progress_handle rsimg";c.appendChild(k);p.rsid=e;p.parent=c;p.ref=k;e=$rs.css(k,"left");null!==e&&(f.left=parseInt(e.replace(/px/i,"")));e=$rs.css(k,"top");null!==e&&(f.top=parseInt(e.replace(/px/i,"")));-1<f.initval&&this.jumpTo(f.initval);f.labelStart&&(e=document.createElement("span"),e.className="slider-label-start",e.innerHTML=f.labelStart,c.appendChild(e));f.labelEnd&&(e=document.createElement("span"),e.className="slider-label-end",e.innerHTML=f.labelEnd,
c.appendChild(e));a.initElement(k)}},jumpTo:function(a){if(isNaN(a))return!1;var b=101,e=a;-1<f.steps&&(a=Math.round(a),b=f.steps+1);if(-1<a&&a<b){var k=f.width,m=f.left,n="left";"v"==f.dir&&(k=f.height,m=f.top,n="top",a=b-1-a);p.ref.style[n]=k/(b-1)*a+m+"px";$rs.setAttr($rs.findIn(p.ref,"a.keyLink"),"aria-valuenow",e)}},setCurrentValue:function(a){e=a},getInstance:function(){return p},getContainer:function(){return p.parent},releaseElement:function(){a.releaseElement()},startDragKeys:function(c,
b){a.startDragKeys.call(c,b)},disabled:function(){if(arguments)u=arguments[0];else return u}}};
ReadSpeaker.ui.Player=function(a){var f=function(a){a=a||window.event;a.returnValue=!1;if(a=a.originalEvent)a.cancelBubble=!0,a.returnValue=!1;a&&a.preventDefault&&a.preventDefault();a&&a.stopPropagation&&a.stopPropagation()},p=rspkr.getID(),y=this,t=[],n=0,A=!1,w=null,u=!1,e={_play:null,_pause:null,_stop:null,_vol:null,_settings:null,_dl:null,_closer:null,_powered:null,_get:function(b,c){var e;b="_"+b;e=a?this[b]&&0<this[b].length?this[b]:this[b]=$rs.findIn(a,c):null;return e==[]?null:e},play:function(){return this._get("play",
".rsbtn_play")},pause:function(){return this._get("pause",".rsbtn_pause")},stop:function(){return this._get("stop",".rsbtn_stop")},vol:function(){return this._get("vol",".rsbtn_volume")},settings:function(){return this._get("settings",".rsbtn_settings")},dl:function(){return this._get("dl",".rsbtn_dl")},pin:function(){return this._get("pin",".rsbtn_pin")},powered:function(){return this._get("powered",".rsbtn_powered")},closer:function(){return this._get("closer",".rsbtn_closer")},nosound:function(){return this._get("nosound",
".rsbtn_nosound")},setPlayPause:function(a){rspkr.log("[rspkr.ui.Player.setPlayPause("+a+")]");a=a?$rs.getAttr(this.pause(),"data-rsphrase-play"):$rs.getAttr(this.pause(),"data-rsphrase-pause");$rs.setAttr(this.pause(),"title",rspkr.c.decodeEntities(a));$rs.findIn(this.pause(),".rsbtn_btnlabel").innerHTML=a}},v=!1,c=[],b={play:function(){rspkr.c.dispatchEvent("onUIBeforePlay");rspkr.log("[rspkr.ui.handlers.play]");c.progress&&c.progress.disabled(!1);b.setStateClass(a,"rsplaying");rspkr.basicMode&&
b.setStateClass($rs.findIn(a,".rsbtn_exp"),"rsplaying");$rs.addClass($rs.findIn(a,".rsbtn_progress_container"),"rsloading");e.setPlayPause(!1);if(rspkr.ui.getActivePlayer()&&rspkr.ui.getActivePlayer().getContainer()==a)rspkr.pl.play(),u&&rspkr.pl.getProgress.apply(rspkr.pl,[!0,k,y]),rspkr.c.addEvent("onBeforeSyncInit",function(){u=!0;rspkr.pl.getProgress.apply(rspkr.pl,[!0,k,y])}),"flash"===rspkr.pl.adapter&&!rspkr.displog.onVolumeAdjusted&&rspkr.pl.setVolume(parseInt(rspkr.st.get("hlvol")||"100")),
rspkr.c.dispatchEvent("onUIAfterPlay"),rspkr.cfg.execCallback("cb.ui.play",a);else{rspkr.ui.getActivePlayer()&&rspkr.ui.getActivePlayer().close();var h=$rs.findIn(a,".rsbtn_play");window.readpage(h)}},pause:function(){rspkr.log("[rspkr.ui.handlers.pause]");b.setStateClass(a,"rspaused");rspkr.basicMode&&b.setStateClass($rs.findIn(a,".rsbtn_exp"),"rspaused");e.setPlayPause(!0);rspkr.pl.pause();rspkr.pl.getProgress(!1);rspkr.c.dispatchEvent("onUIPause");rspkr.cfg.execCallback("cb.ui.pause",a);rspkr.log("ReadSpeaker.ui.pause")},
stop:function(){rspkr.log("[rspkr.ui.handlers.stop]");c.progress&&c.progress.disabled(!0);b.setStateClass(a,"rsstopped");$rs.removeClass($rs.findIn(a,".rsbtn_progress_container"),"rsloading");rspkr.basicMode&&b.setStateClass($rs.findIn(a,".rsbtn_exp"),"rsstopped");e.setPlayPause(!0);$rs.setAttr(a,"data-readspeaker-current",0);c.progress&&(c.progress.jumpTo(0),l(0));rspkr.pl.stop();rspkr.pl.getProgress(!1);rspkr.c.dispatchEvent("onUIStop",a);rspkr.cfg.execCallback("cb.ui.stop",a);document.getElementById("rslightbox_contentcontainer")&&
$rs.isVisible(document.getElementById("rslightbox_contentcontainer"))||e.pause().focus();rspkr.HL.chunking&&1<rspkr.HL.chunking.currentChunkNumber&&(rspkr.HL.chunking.destroy(),rspkr.pl.hasOwnProperty("releaseAdapter")&&rspkr.pl.releaseAdapter());rspkr.log("ReadSpeaker.ui.stop")},setStateClass:function(a,b){a&&($rs.removeClass(a,"rspaused rsstopped rsplaying"),$rs.addClass(a,b))},vol:function(b){var e=$rs.findIn(a,".rsbtn_volume_container"),f=$rs.findIn(a,".rsbtn_volume");b=b.originalEvent;var g=
function(a){var b=a.originalEvent,b=$rs.closest(b.srcElement||b.originalTarget,".rsbtn_volume_container");if("click"===a.type){if(void 0===b||$rs.isArray(b)&&!b.length)$rs.css(e,"display","none"),$rs.unregEvent(document.body,"click",g),$rs.unregEvent(document.body,"keyup",g)}else"keyup"===a.type&&27===a.keyCode&&($rs.css(e,"display","none"),$rs.unregEvent(document.body,"click",g),$rs.unregEvent(document.body,"keyup",g))};$rs.css(e,"left",f.offsetLeft+"px");$rs.css(e,"display","none"==$rs.css(e,"display")?
"block":"none");"block"===$rs.css(e,"display")?($rs.regEvent(document.body,"click",g),$rs.regEvent(document.body,"keyup",g)):($rs.unregEvent(document.body,"click",g),$rs.unregEvent(document.body,"keyup",g));b&&b.stopPropagation&&b.stopPropagation();b.cancelBubble=!0;f={keyCode:13};b=$rs.findIn(e,".keyLink");try{c.vol.startDragKeys(b,f)}catch(l){rspkr.log("[rspkr.ui.handlers.vol] Error accessing object _sliders['vol']")}return!1},settings:function(){$rs.hasClass(a,"rsplaying")&&this.pause();rspkr.ui.Lightbox.show(rspkr.st.getHTML(),
rspkr.st.getButtons(),!0,function(a){var b=$rs.get("rslightbox_closer"),c=function(){document.removeEventListener?b.removeEventListener("click",c,!1):document.detachEvent&&document.detachEvent("onclick",c);rspkr.c.dispatchEvent("onSettingsClosed",window,[])};$rs.regEvent(b,"click",c);rspkr.ui.addClickEvents();rspkr.c.dispatchEvent("onSettingsLoaded",window,[]);rspkr.cfg.execCallback("cb.ui.settingsopened",a)})},close:function(h){b.pin(!0);h=h||!1;var f=rspkr.pl,g=!1;rspkr.HL.chunking&&rspkr.HL.chunking.destroy();
h||rspkr.cfg.execCallback("cb.ui.beforeclose",a);f.hasOwnProperty("getProgress")&&rspkr.pl.getProgress(!1);f.hasOwnProperty("releaseAdapter")&&rspkr.pl.releaseAdapter();$rs.setAttr(a,"data-readspeaker-current",0);c.progress&&(c.progress.jumpTo(0),l(0));$rs.removeClass(a,"rsstopped rsplaying rspaused rsexpanded");if(rspkr.basicMode){var k;(k=$rs.findIn(a,".rsbtn_play"))&&$rs.removeClass(k,"rsexpanded")}$rs.hasClass(a,"rsfloating")&&($rs.removeClass(a,rspkr.ui.rsbtnClass),rspkr.basicMode&&($rs.removeClass(a,
"rsvisible"),$rs.addClass(a,"rshidden")));e.setPlayPause(!0);$rs.hasClass(a,"rspopup")&&(g=!0,$rs.removeClass(a,"rspopup"),$rs.css(a,"display","none"),a.parentNode.removeChild(a));$rs.css(a,"width","auto");delete rspkr.displog.onVolumeAdjusted;h||(rspkr.c.dispatchEvent("onUIClosePlayer",a,["userclick"]),rspkr.cfg.execCallback("cb.ui.close",a),rspkr.log("ReadSpeaker.ui.close: "+a));!h&&!1===g&&rspkr.ui.focus($rs.findIn($rs.get(a),".rsbtn_play"))},dl:function(){$rs.hasClass(a,"rsplaying")&&this.pause();
var b=$rs.getAttr($rs.findIn(a,".rsbtn_play"),"href"),c=b?rspkr.c.data.getSaveData("dialog",b):rspkr.c.data.getSaveData("dialog"),e=!1;rspkr.log("[rspkr.ui.handlers.dl] Savelink: "+c);rspkr.u.Lightbox.show(this.getDlDialog(),this.getDlButtons(),!0,function(){var a=$rs.get("#rsdl_button_accept"),b=$rs.get("#rsdl_button_decline");a&&$rs.regEvent(a,"click",function(b){rspkr.u.Lightbox.hide(b);e="iOS"!==rspkr.c.data.browser.OS&&0<rspkr.c.data.selectedHTML.length?!0:"iOS"!==rspkr.c.data.browser.OS&&!0===
rspkr.cfg.item("general.usePost")?!0:!1;if(!0===e){b=null;if(document.getElementById("dliframe"))b=document.getElementById("dliframe");else{if(document.selection)try{b=document.createElement('<iframe name="dliframe">')}catch(h){b=document.createElement("iframe")}else b=document.createElement("iframe");b.name="dliframe";b.setAttribute("id","dliframe");b.setAttribute("style","display: none; position: absolute;");b.style.display="none";var f=document.getElementsByTagName("body"),g=null;0<f.length&&(g=
f.item(0));if(g)g.appendChild(b);else return}b.src=c;return!1}$rs.setAttr(a,"href",c);return!0});b&&($rs.regEvent(b,"click",function(a){f(a);rspkr.u.Lightbox.hide(a)}),setTimeout(function(){rspkr.ui.focus(b)},200));rspkr.c.dispatchEvent("onDownloadLoaded",window,[])})},pin:function(b,c){var f=a.id+"_pinnedHome",g=document.getElementById(f);c=c?!0:!1;if(!$rs.hasClass(e.pin(),"pinned")&&!b){if($rs.addClass(e.pin(),"pinned"),!g){var l=function(a,b){return window.getComputedStyle?window.getComputedStyle(a)[b]:
a.currentStyle?a.currentStyle[b]:a.style[b]},g=$rs.clone(a,!1,!0),k=a.offsetLeft,n=a.offsetTop;if(!c){g.style.width=l(a,"width").replace(/[^-\d\.]/g,"")-2+"px";g.style.height=l(a,"height").replace(/[^-\d\.]/g,"")-2+"px";for(var m="position left right top bottom margin-left margin-right margin-top margin-bottom".split(" "),r=0,B;B=m[r];r++){var p=$rs.css(a,B);$rs.setAttr(a,"data-css-"+B,p);p=l(a,B);"auto"!=p&&(g.style[B]=p)}g.className="rsbtn_pinnedHome rsbtn";for(g.id=f;g.hasChildNodes();)g.removeChild(g.lastChild);
a.parentElement.insertBefore(g,a)}a.style.position="fixed";a.style.top=n-$rs.scrollTop(document)+"px";a.style.left=k-$rs.scrollLeft(document)+"px"}}else if($rs.hasClass(e.pin(),"pinned")||b)if($rs.removeClass(e.pin(),"pinned"),g)for(g.parentNode.removeChild(g),m="position left right top bottom margin-left margin-right margin-top margin-bottom".split(" "),r=0;B=m[r];r++)p=$rs.getAttr(a,"data-css-"+B),$rs.css(a,B,p)},getDlDialog:function(){var a=rspkr.cfg.item("ui.dldialog").join("\n"),b={};b.rsTERMS_OF_USE_HEADINGrs=
rspkr.cfg.getPhrase("touheading");b.rsTERMS_OF_USE_BODYrs=rspkr.cfg.getPhrase("toubody");return rspkr.st.r().replaceTokens(a,b)},getDlButtons:function(){var a=rspkr.cfg.item("ui.dlbuttons").join("\n"),b={};b.rsTERMS_OF_USE_ACCEPTrs=rspkr.cfg.getPhrase("touaccept");b.rsTERMS_OF_USE_DECLINErs=rspkr.cfg.getPhrase("toudecline");return rspkr.st.r().replaceTokens(a,b)},nosound:function(){var a=rspkr.c.data.getSaveData("link");$rs.setAttr(e.nosound(),"href",a);return!0}},l=function(b){b=100<b?100:b;var c=
$rs.findIn(a,".rsbtn_progress_played");"object"===typeof c&&$rs.css(c,"width",b+"%");rspkr.cfg.execCallback("cb.ui.progresschanged",a,[b])},k=function(b){if(b.length){var e=parseInt(b[0]);b=parseInt(b[1]);var g=0==b?0:Math.round(e/b*100),f=$rs.findIn(a,".rsbtn_current_time"),k=$rs.findIn(a,".rsbtn_total_time"),n,r;c.progress&&(c.progress.setCurrentValue(g),v||(c.progress.jumpTo(g),l(g),f&&(f.innerHTML=n=m(e)),k&&(k.innerHTML=r=m(b)),rspkr.cfg.execCallback("cb.ui.timeupdated",a,[n,r])));rspkr.log("[rspkr.player.updateProgress] current time: "+
e+" total time: "+b);$rs.setAttr(a,"data-readspeaker-current",e);$rs.setAttr(a,"data-readspeaker-buffered",b);0<e&&$rs.removeClass($rs.findIn(a,".rsbtn_progress_container"),"rsloading")}},m=function(a){a/=1E3;var b=parseInt(a%60),c=parseInt(a/60%60);a=parseInt(a/60/60%60);return(10>a?"0"+a:a.toString())+":"+(10>c?"0"+c:c.toString())+":"+(10>b?"0"+b:b.toString())},r=function(){v=!0},g=function(b){rspkr.log("_dropProgress ("+b+")",5);b&&(b=b/100*$rs.getAttr(a,"data-readspeaker-buffered")/1E3,rspkr.pl.setProgress(b));
v=!1},z=function(a){g(a)},D=function(b){rspkr.log("_dropVolume, "+b,5);b=0>b?0:20*b;c.vol&&c.vol.jumpTo(b/20);rspkr.pl.setVolume(b);rspkr.st.set("hlvol",b);rspkr.cfg.execCallback("cb.ui.volumechanged",a,[b]);return!1},E=function(b,e){if("keyLink"===b.className){var g="";$rs.hasClass(e,"rsbtn_volume_handle")?g="vol":$rs.hasClass(e,"rsbtn_progress_handle")&&(g="progress");var f={keyCode:13};c[g].startDragKeys(b,f)}else $rs.hasClass(e,"rsbtn_volume")&&(f={keyCode:13},g=$rs.findIn(a,".rsbtn_volume_container"),
g=$rs.findIn(g,".keyLink"),c.vol.startDragKeys(g,f))},C=function(a,b){if("keyLink"===a.className){var e="";$rs.hasClass(b,"rsbtn_volume_handle")?e="vol":$rs.hasClass(b,"rsbtn_progress_handle")&&(e="progress");c[e].releaseElement();v=!1}};return{init:function(){t.push([this.show,[]])},initVolume:function(){if(!$rs.isArray($rs.findIn($rs.get(a),".rsbtn_volume_slider"))){var b=rspkr.cfg,e=rspkr.st.get("hlvol")||"100",e=5*(parseInt(e)/100);c.vol=new rspkr.ui.Slider;c.vol.init($rs.findIn(a,".rsbtn_volume_slider"),
{handleClass:b.item("ui.volumeHandleClass")||"rsbtn_volume_handle rsimg",dir:b.item("ui.volumeDir")||"v",steps:5,nudge:1,initval:e,dragging:D,click:D,labelDragHandle:b.getPhrase("slidervolumedesc")});b=$rs.findIn($rs.get(a),".rsbtn_volume_handle a");ui.addFocusHandler(b,!1,b.parentNode)}},show:function(h){h=h?!0:!1;var l=$rs.hasClass(a,"rsexpanded");$rs.rsid(a);a.id=p=a.id||rspkr.getID();ui=rspkr.ui;$rs.hasClass(a,rspkr.ui.rsbtnClass)||$rs.addClass(a,rspkr.ui.rsbtnClass);var k=null,k=rspkr.cfg,m=
rspkr.cfg.getPhrases(rspkr.c.data.getParam("lang"));if(0==$rs.findIn(a,".rsbtn_exp").length){var t=$rs.hasClass(a,"rspopup")?k.item("ui.popupplayer"):k.item("ui.player"),k=document.createElement("div");k.className="rsbtn_exp rsimg rspart";k.innerHTML+=t.join("\n");a.appendChild(k)}k=e.pin();t="Explorer"==rspkr.c.data.browser.name&&8>rspkr.c.data.browser.version;$rs.isArray(k)&&0==k.length&&(k=void 0);k&&!t&&rspkr.cfg.item("ui.usePin")?$rs.removeClass(k,"turnedOff"):k&&k.parentElement.removeChild(k);
if(m){k=function(a,b){var c=$rs.findIn(a,".rsbtn_btnlabel");$rs.isArray(c)||(c=[c]);0<c.length&&(c[0].innerHTML=b)};e.pause()&&($rs.setAttr(e.pause(),"data-rsphrase-pause",m.pause),$rs.setAttr(e.pause(),"data-rsphrase-play",m.play),$rs.setAttr(e.pause(),"title",rspkr.c.decodeEntities(m.pause)),k(e.pause(),rspkr.c.decodeEntities(m.pause)));e.stop()&&($rs.setAttr(e.stop(),"title",rspkr.c.decodeEntities(m.stop)),k(e.stop(),rspkr.c.decodeEntities(m.stop)));e.vol()&&($rs.setAttr(e.vol(),"title",rspkr.c.decodeEntities(m.volume)),
k(e.vol(),rspkr.c.decodeEntities(m.volume)));e.settings()&&($rs.setAttr(e.settings(),"title",rspkr.c.decodeEntities(m.settings)),k(e.settings(),rspkr.c.decodeEntities(m.settings)));e.dl()&&($rs.setAttr(e.dl(),"title",rspkr.c.decodeEntities(m.download)),k(e.dl(),rspkr.c.decodeEntities(m.download)));if(e.powered()){var t=$rs.findIn(e.powered(),".rsbtn_btnlabel"),w=m.speechenabled.match(/.*href="([^"]*)"/i).pop(),u=m.newwindow,y=document.createElement("p");y.innerHTML=m.speechenabled;u=(y.innerText||
y.textContent)+(u?" ("+u+")":"");t&&(t.innerHTML=m.speechenabled);$rs.setAttr(e.powered(),"title",u);$rs.setAttr(e.powered(),"data-readspeaker-href",w);t=$rs.getAttr(e.powered(),"data-rsevent-id");(!t||rs.l.f.eq.store[t]&&!rs.l.f.eq.store[t].click)&&$rs.regEvent(e.powered(),"click",function(){window.open($rs.getAttr(this,"data-readspeaker-href"))})}e.closer()&&($rs.setAttr(e.closer(),"title",rspkr.c.decodeEntities(m.closeplayer)),k(e.closer(),rspkr.c.decodeEntities(m.closeplayer)))}m=rspkr.c.data.browser;
/safari/i.test(m.name)&&/iphone|ipad|ios/i.test(m.OS)||$rs.addClass(a,"rs-no-touch");m=$rs.findIn(a,".rsbtn_status_overlay");$rs.isArray(m)||$rs.css(m,"display","none");"fallback"===rspkr.pl.adapter&&(rspkr.ui.showOverlay("nosound",a),$rs.addClass(a,"rsstopped"));$rs.addClass(a,"rsexpanded");if(rspkr.basicMode){var x;(x=$rs.findIn(a,".rsbtn_play"))&&$rs.addClass(x,"rsexpanded")}!A&&!l&&(e.stop()&&($rs.regEvent(e.stop(),"click",function(a){f(a);b.stop()}),ui.addFocusHandler(e.stop())),e.pause()&&($rs.regEvent(e.pause(),
"click",function(c){f(c);$rs.hasClass(a,"rsplaying")?b.pause():($rs.hasClass(a,"rsstopped")||$rs.hasClass(a,"rspaused"))&&b.play()}),ui.addFocusHandler(e.pause())),e.closer()&&($rs.regEvent(e.closer(),"click",function(a){f(a);b.close()}),ui.addFocusHandler(e.closer())),e.vol()&&($rs.regEvent(e.vol(),"click",function(a){f(a);b.vol(a)}),ui.addFocusHandler(e.vol())),e.dl()&&($rs.regEvent(e.dl(),"click",function(a){f(a);return b.dl(a)}),ui.addFocusHandler(e.dl())),e.settings()&&($rs.regEvent(e.settings(),
"click",function(a){f(a);b.settings()}),ui.addFocusHandler(e.settings())),e.pin()&&($rs.regEvent(e.pin(),"click",function(a){f(a);b.pin()}),ui.addFocusHandler(e.pin())),x=rspkr.cfg,$rs.setAttr(a,"data-readspeaker-current",0),$rs.setAttr(a,"data-readspeaker-buffered",0),$rs.isArray($rs.findIn($rs.get(a),".rsbtn_progress_container"))||(c.progress=new rspkr.ui.Slider,c.progress.init($rs.findIn($rs.get(a),".rsbtn_progress_container"),{handleClass:x.item("ui.progressHandleClass")||"rsbtn_progress_handle rsimg",
dir:x.item("ui.progressDir")||"h",nudge:5,start:r,dragging:g,click:z,labelDragHandle:x.getPhrase("sliderseek")}),l=$rs.findIn($rs.get(a),".rsbtn_progress_handle a"),ui.addFocusHandler(l,!1,l.parentNode)),$rs.isArray($rs.findIn($rs.get(a),".rsbtn_volume_slider"))||(l=rspkr.st.get("hlvol")||"100",l=5*(parseInt(l)/100),c.vol=new rspkr.ui.Slider,c.vol.init($rs.findIn(a,".rsbtn_volume_slider"),{handleClass:x.item("ui.volumeHandleClass")||"rsbtn_volume_handle rsimg",dir:x.item("ui.volumeDir")||"v",steps:5,
nudge:1,initval:l,dragging:D,click:D,labelDragHandle:x.getPhrase("slidervolumedesc")}),l=$rs.findIn($rs.get(a),".rsbtn_volume_handle a"),ui.addFocusHandler(l,!1,l.parentNode)),rspkr.Common.addEvent("onFocusIn",E),rspkr.Common.addEvent("onFocusOut",C),rspkr.cfg.execCallback("cb.ui.open",a),A=!0);$rs.findIn(a,".rsbtn_powered")&&(x=$rs.findIn(a,".rsbtn_powered .rsbtn_btnlabel a"))&&((/Chrome|Safari|Opera/gi.test(rs.c.data.browser.name)||/Explorer/gi.test(rs.c.data.browser.name)&&8<=rs.c.data.browser.version)&&
$rs.regEvent(x,"click",function(a){f(a)}),x.innerHTML='<span class="rsbtn_label_read">Read</span><span class="rsbtn_label_speaker">Speaker</span><span class="rsbtn_label_icon rsimg"></span>');"0"!=$rs.getAttr(a,"data-readspeaker-current")&&(rspkr.pl.releaseAdapter(),$rs.setAttr(a,"data-readspeaker-current",0));"fallback"===rspkr.pl.adapter||h?(c.progress&&c.progress.disabled(!0),b.setStateClass(a,"rsstopped"),$rs.removeClass($rs.findIn(a,".rsbtn_progress_container"),"rsloading"),rspkr.basicMode&&
b.setStateClass($rs.findIn(a,".rsbtn_exp"),"rsstopped")):(b.play(),rspkr.ui.focus(e.pause()));h=(h=a)||a;h=$rs.clone(h,!0,!0);h.id=rspkr.getID();document.body.appendChild(h);$rs.css(h,{position:"absolute",top:"0",left:"0",display:"block",width:"auto"});$rs.css(h,"float","none");$rs.addClass(h,"rsexpanded");x=$rs.outerWidth(h)+3;h.style.display="none";document.body.removeChild(h);n=x;isNaN(n)||$rs.css(a,"width",n+(/[Ee]xplorer/.test(ReadSpeaker.c.data.browser.name)?1:0)+"px");$rs.hasClass(a,"rspopup")&&
!rspkr.cfg.item("ui.pinnedPopup")&&!rspkr.basicMode&&b.pin(!1,!0)},close:function(a){b.close(a)},stop:function(){b.stop()},nosound:function(){return b.nosound()},pause:function(){b.pause()},play:function(){b.play()},dl:function(a){b.dl(a)},settings:function(){b.settings()},vol:function(a){b.vol(a)},pin:function(a,c){b.pin(a,c)},restart:function(){rspkr.log("[rspkr.ui.restart]");b.stop();window.setTimeout(function(){b.play()},500);return!1},updateProgress:function(a){k(a)},setProgress:function(a){g(a)},
getContainer:function(){return a},getID:function(){return p},getWidth:function(){return n},setHref:function(a){w=a},getHref:function(){return w}}};
ReadSpeaker.ui.Lightbox=function(){var a=null,f=null,p=null,y=null,t=null,n=null,A,w=[],u=function(a){a=a||window.event;a.returnValue=!1;if(a=a.originalEvent)a.cancelBubble=!0,a.returnValue=!1;a&&a.preventDefault&&a.preventDefault();a&&a.stopPropagation&&a.stopPropagation()},e=function(){var a=$rs.css(n,"display");$rs.css(n,"display","none");var c=$rs.height(window),e=$rs.height(document),f=parseInt($rs.css(document.documentElement,"width")),r=$rs.width(document),g=$rs.absOffset(document.body),p=
0,u=0;isNaN(f)&&(f=$rs.width(window));g.left&&(u=g.left);g.top&&(p=g.top);$rs.css(t,{width:(r>f?r:f)+"px",height:(e>c?e:c)+"px",top:"-"+Math.abs(p)+"px",left:"-"+Math.abs(u)+"px"});$rs.css(n,"display",a);v()},v=function(){var a=$rs.outerWidth(n),c=$rs.outerHeight(n),e=$rs.width(window),f=$rs.height(window),c=A+80+50<f?A+80:f-50;n.style.height=c+"px";$rs.get("#rslightbox_content").style.height=c-80+"px";c>f?(n.style.top=$rs.scrollTop(document)+"px",n.style.marginTop="10px"):(n.style.top=f/2+"px",n.style.marginTop=
-(c/2-$rs.scrollTop(document))+"px");a>e?(n.style.left=$rs.scrollLeft(document)+"px",n.style.marginLeft="0"):(n.style.left="50%",n.style.marginLeft=-(a/2-$rs.scrollLeft(document))+"px")},c=function(a){27===a.keyCode&&rspkr.ui.Lightbox.hide()};return{init:function(){var b=rspkr.pub.Config;a=b.item("ui.overlay.overlayStyles");f=b.item("ui.overlay.contentStyles");p=b.item("ui.overlay.contentTemplate");document.querySelectorAll||(d=document,s=d.createStyleSheet(),d.querySelectorAll=function(a,b,c,e,g){g=
d.all;b=[];a=a.replace(/\[for\b/gi,"[htmlFor").split(",");for(c=a.length;c--;){s.addRule(a[c],"k:v");for(e=g.length;e--;)g[e].currentStyle.k&&b.push(g[e]);s.removeRule(0)}return b});rspkr.log("[rspkr.ui.Lightbox] Heartbeat!")},show:function(b,l,k,m,r){for(var g=0,z=document.body.getElementsByTagName("*"),v;v=z[g];g++)-1!=v.tabIndex&&(w.push([v,v.tabIndex]),v.tabIndex=-1);if("Explorer"!=rs.c.data.browser.name||6!=rs.c.data.browser.version)for(v=document.querySelectorAll("body > *"),g=0;z=v[g];g++)if("rslightbox_overlay"!=
z.id&&"rslightbox_contentcontainer"!=z.id&&"script"!=z.tagName.toLowerCase()){var E=z.getAttribute("aria-hidden");E&&z.setAttribute("data-original-aria-hidden",E);z.setAttribute("aria-hidden","true")}b=b||"";k=k||!1;t?(t.style.display="",n.style.display=""):(t=document.createElement("div"),t.id="rslightbox_overlay",n=document.createElement("div"),n.id="rslightbox_contentcontainer",n.innerHTML=rspkr.st.r().replaceTokens(p.join("\n"),{rsLIGHTBOX_CLOSE_LABELrs:rspkr.cfg.getPhrase("close")}),$rs.setAttr(t,
"style",a.join(";")),$rs.setAttr(n,"style",f.join(";")),document.body.appendChild(t),document.body.appendChild(n),rspkr.evt("onSettingsLoaded",{func:rspkr.st.r().handlers.changed.addButtonEvents,context:rspkr.st.r().handlers.changed,params:[this]}));g=$rs.get("rslightbox_closer");rspkr.ui.addFocusHandler(g,!1);$rs.regEvent(g,"click",function(a){u(a);rspkr.ui.Lightbox.hide(a)});$rs.regEvent(t,"click",rspkr.ui.Lightbox.hide);$rs.regEvent(document.body,"keyup",c);(z=document.documentElement)&&document.all&&
(z.style.overflowX=z.style.overflowY="hidden");if(b!=y||k)k=rspkr.cfg.getPhrase("close"),$rs.setAttr(g,"title",k),$rs.findIn(g,".rsbtn_btnlabel").innerHTML=k,$rs.get("#rslightbox_content").innerHTML="",$rs.css("#rslightbox_content","height","auto"),/^http/i.test(b)?$rs.findIn("#rslightbox_content","iframe").length||(k=document.createElement("iframe"),k.src=b,k.className="rslightbox-iframe",void 0===r&&(r=2E3),$rs.get("#rslightbox_content").appendChild(k)):"<"==b.substr(0,1)&&($rs.get("#rslightbox_content").innerHTML=
b),$rs.get("#rslightbox_buttons").innerHTML=l,y=b,"ar_ar"==rs.c.data.params.lang&&(-1==n.className.indexOf("rtl")&&(n.className=(n.className+" rtl").replace(/^\s+|\s+$/g,"")),$rs.setAttr($rs.findIn(n,"legend"),"align","right"));A=void 0===r||isNaN(r)?rspkr.basicMode?$rs.get("#rslightbox_content").scrollHeight:$rs.get("#rslightbox_content").clientHeight:r;b=$rs.findIn("#rslightbox_content",".rsform-row");for(g=0;g<b.length;g++)for(l=$rs.findIn(b[g],"input, a, select"),$rs.isArray(l)||(l=[l]),z=0;z<
l.length;z++)rspkr.ui.addFocusHandler(l[z],!1,b[g]);var C=$rs.findIn("#rslightbox_buttons",".rssettings-button-close");rspkr.ui.addFocusHandler(C,!1);$rs.regEvent(C,"click",function(a){u(a)});(b=$rs.findIn("#rsform_wrapper",".rssettings-button-gotobottom"))&&!$rs.isArray(b)&&rspkr.ui.addFocusHandler(b,!1);(b=$rs.findIn("#rslightbox_buttons",".rssettings-button-gototop"))&&!$rs.isArray(b)&&rspkr.ui.addFocusHandler(b,!1);var h=$rs.findIn("#rslightbox_content","input");$rs.isArray(h)&&0<h.length?setTimeout(function(){rspkr.ui.focus(h[0]);
rspkr.Common.addEvent("onFocusIn",function(a){a.className&&$rs.hasClass(a,"rssettings-button-gototop")?rspkr.ui.focus(h[0]):a.className&&$rs.hasClass(a,"rssettings-button-gotobottom")&&rspkr.ui.focus(C)})},200):$rs.isArray(h)||setTimeout(function(){rspkr.ui.focus(h)},200);e();$rs.regEvent(window,"resize",e);"function"==typeof m&&m.apply(this,[n])},hide:function(a){for(;0<w.length;){var f=w.pop();f[0].tabIndex=f[1]}if("Explorer"!=rs.c.data.browser.name||6!=rs.c.data.browser.version){a=document.querySelectorAll("body > *");
for(var f=0,k;k=a[f];f++){var m=k.getAttribute("data-original-aria-hidden");m?(k.setAttribute("aria-hidden",m),k.removeAttribute("data-original-aria-hidden")):k.removeAttribute("aria-hidden")}}u(a);t.style.display="none";n.style.display="none";$rs.unregEvent(window,"resize",e);$rs.unregEvent($rs.get("#rslightbox_closer"),"click",rspkr.ui.Lightbox.hide);$rs.unregEvent(t,"click",rspkr.ui.Lightbox.hide);$rs.unregEvent(document.body,"keyup",c);(a=document.documentElement)&&document.all&&(a.style.overflowX=
a.style.overflowY="auto");rspkr.ui.updateFocus();rspkr.c.dispatchEvent("onSettingsClosed",window,[])},reposition:v}}();
